name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  automation-test-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use node.js ${{ matrix.node-version }}
      uses: action/setup-node@v2
      with:
        node-version: $ {{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm run ci:test